# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

women = Category.create(name: "ウィメンズ")
men = Category.create(name: "メンズ")
kidslady = Category.create(name: "キッズ(レディース)")
kidsboy = Category.create(name: "キッズ(ボーイ)")
baby = Category.create(name: "ベビー")
beauty = Category.create(name: "コスメ・香水・美容")
book = Category.create(name: "本・音楽・ゲーム")
sport = Category.create(name: "スポーツ・レジャー")

# レディースの子カテゴリ
women_tops = women.children.create(name: "トップス")
women_jacket = women.children.create(name: "ジャケット/アウター")
women_onepiece = women.children.create(name: "ワンピース")
women_overalls = women.children.create(name: "オールインワン・サロペット")
women_suits = women.children.create(name: "スーツ/ネクタイ")
women_skirt = women.children.create(name: "スカート")
women_pants = women.children.create(name: "パンツ")
women_shoes = women.children.create(name: "シューズ")
women_legwear = women.children.create(name: "レッグウェア")
women_bag = women.children.create(name: "バッグ")
women_hat = women.children.create(name: "帽子")
women_accessory = women.children.create(name: "アクセサリー")
women_hair = women.children.create(name: "ヘアアクセサリー")
women_item = women.children.create(name: "ファッション雑貨")
women_wallet = women.children.create(name: "財布・小物")
women_clock = women.children.create(name: "時計")
women_kimono = women.children.create(name: "水着/着物・浴衣")
women_underwear = women.children.create(name: "アンダーウェア")
women_body = women.children.create(name: "ボディ・ヘアケア/コンタクト")
women_other = women.children.create(name: "その他")

# レディースの孫カテゴリ
women_tops.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ/ブラウス(半袖/袖なし)"}, {name: "シャツ/ブラウス(七分/長袖)"}, {name: "ポロシャツ"}, {name: "ニット・セーター"}, {name: "ベスト/ジレ"}, {name: "パーカー"}, {name: "トレーナー/スウェット"}, {name: "カーディガン/ボレロ"}, {name: "アンサンブル"}, {name: "ジャージ"}, {name: "タンクトップ"}, {name: "キャミソール"}, {name: "その他"}])
women_jacket.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "ライダースジャケット"}, {name: "ジャンパー/ブルゾン"}, {name: "カバーオール"}, {name: "ミリタリージャケット"}, {name: "MA-1"}, {name: "ダウンベスト"}, {name: "ダウンジャケット/コート"}, {name: "ダッフルコート"}, {name: "モッズコート"}, {name: "ピーコート"}, {name: "ステンカラーコート"}, {name: "トレンチコート"}, {name: "チェスターコート"}, {name: "ムートンコート"}, {name: "ナイロンジャケット"}, {name: "マウンテンパーカー"}, {name: "スタジャン"}, {name: "スカジャン"}, {name: "ポンチョ"}, {name: "その他"}])
women_onepiece.children.create([{name: "ミニワンピース"}, {name: "ひざ丈ワンピース"}, {name: "ロングワンピース"}, {name: "シャツワンピース"}, {name: "ジャンパースカート"}, {name: "チュニック"}, {name: "ドレス"}, {name: "その他"}])
women_overalls.children.create([{name: "オールインワン・サロペット"}, {name: "つなぎ・オールインワン"}, {name: "その他"}])
women_suits.children.create([{name: "スーツジャケット"}, {name: "スーツベスト"}, {name: "スーツパンツ"}, {name: "スーツスカート"}, {name: "セットアップ"}, {name: "ネクタイ"}, {name: "蝶ネクタイ"}, {name: "ネクタイピン"}, {name: "カフリンクス"}, {name: "その他"}])
women_skirt.children.create([{name: "ミニスカート"}, {name: "ひざ丈スカート"}, {name: "ロングスカート"}, {name: "デニムスカート"}, {name: "その他"}])
women_pants.children.create([{name: "デニム/ジーンズ"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "チノパン"}, {name: "スラックス"}, {name: "ショートパンツ"}, {name: "カジュアルパンツ"}, {name: "ハーフパンツ"}, {name: "クロップドパンツ"}, {name: "サルエルパンツ"}, {name: "ガウチョパンツ"}, {name: "その他"}])
women_shoes.children.create([{name: "スニーカー"}, {name: "スリッポン"}, {name: "サンダル"}, {name: "パンプス"}, {name: "ブーツ"}, {name: "ブーティ"}, {name: "ドレスシューズ"}, {name: "バレエシューズ"}, {name: "ローファー"}, {name: "モカシン/デッキシューズ"}, {name: "レインシューズ"}, {name: "ビーチサンダル"}, {name: "その他"}])
women_legwear.children.create([{name: "ソックス/靴下"}, {name: "タイツ・ストッキング"}, {name: "レギンス・スパッツ"}, {name: "レッグウォーマー"}, {name: "その他"}])
women_bag.children.create([{name: "ショルダーバッグ"}, {name: "トートバッグ"}, {name: "バックパック・リュック"}, {name: "ボストンバッグ"}, {name: "ボディバック/ウエストポーチ"}, {name: "ハンドバッグ"}, {name: "クラッチバッグ"}, {name: "メッセンジャーバッグ"}, {name: "ビジネスバッグ"}, {name: "スーツケース・・キャリーバッグ"}, {name: "ドラムバッグ"}, {name: "エコバッグ"}, {name: "かごバッグ"}, {name: "その他"}])
women_hat.children.create([{name: "キャップ"}, {name: "ハット"}, {name: "ニットキャップ・ビーニー"}, {name: "ハンチング・ベレー帽"}, {name: "キャスケット"}, {name: "サンバイザー"}, {name: "その他"}])
women_accessory.children.create([{name: "ネックレス"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "イヤリング(片耳用)"}, {name: "イヤリング(両耳用)"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "アンクレット"}, {name: "チョーカー"}, {name: "ブローチ・コサージュ"}, {name: "チャーム"}, {name: "その他"}])
women_hair.children.create([{name: "ヘアゴム"}, {name: "ヘアバンド"}, {name: "カチューシャ"}, {name: "バレッタ/ヘアクリップ"}, {name: "ヘアピン"}, {name: "シュシュ"}, {name: "ウィッグ"}, {name: "その他"}])
women_item.children.create([{name: "ストール/スヌード"}, {name: "マフラー・ショール"}, {name: "ベルト"}, {name: "サスペンダー"}, {name: "サングラス"}, {name: "メガネ"}, {name: "手袋"}, {name: "ネックウォーマー"}, {name: "イヤマフ"}, {name: "長傘"}, {name: "折りたたみ傘"}, {name: "レインコート/ポンチョ"}, {name: "付け襟"}, {name: "その他"}])
women_wallet.children.create([{name: "財布"}, {name: "コインケース/札入れ"}, {name: "名刺入れ"}, {name: "ポーチ"}, {name: "手鏡/コンパクト"}, {name: "ハンカチ/ハンドタオル"}, {name: "バンダナ・スカーフ"}, {name: "キーホルダー"}, {name: "キーケース/キーアクセサリー"}, {name: "ウォレットチェーン"}, {name: "パスケース"}, {name: "カードケース"}, {name: "パスポートケース"}, {name: "扇子・うちわ"}, {name: "その他"}])
women_clock.children.create([{name: "腕時計"}, {name: "置き時計"}, {name: "掛け時計"}, {name: "その他"}])
women_kimono.children.create([{name: "水着"}, {name: "ラッシュガード"}, {name: "着物"}, {name: "スイムグッズ"}, {name: "浴衣"}, {name: "和装小物"}, {name: "その他"}])
women_underwear.children.create([{name: "ブラ"}, {name: "ショーツ"}, {name: "ブラ＆ショーツ"}, {name: "ルームウェア"}, {name: "その他"}])
women_body.children.create([{name: "香水"}, {name: "コンタクトレンズ・カラコン"}, {name: "ボディクリーム"}, {name: "ボディスクラブ/ピーリング"}, {name: "日焼け止め"}, {name: "ハンドクリーム"}, {name: "シャンプー"}, {name: "コンディショナー/トリートメント"}, {name: "ヘアスタイリング/ヘアワックス"}, {name: "ヘアオイル/ヘアミルク"}, {name: "石鹸/ボディソープ"}, {name: "入浴剤"}, {name: "オーラルケア/歯磨きグッズ"}, {name: "その他"}])
women_other.children.create([{name: "福袋・福箱"}, {name: "ラッピングキッド"}, {name: "採寸ボディスーツ"}, {name: "その他"}])

# メンズの子カテゴリ
men_tops = men.children.create(name: "トップス")
men_jacket = men.children.create(name: "ジャケット/アウター")
men_overalls = men.children.create(name: "オールインワン・サロペット")
men_suits = men.children.create(name: "スーツ/ネクタイ")
men_pants = men.children.create(name: "パンツ")
men_shoes = men.children.create(name: "シューズ")
men_legwear = men.children.create(name: "レッグウェア")
men_bag = men.children.create(name: "バッグ")
men_hat = men.children.create(name: "帽子")
men_accessory = men.children.create(name: "アクセサリー")
men_hair = men.children.create(name: "ヘアアクセサリー")
men_item = men.children.create(name: "ファッション雑貨")
men_wallet = men.children.create(name: "財布・小物")
men_clock = men.children.create(name: "時計")
men_kimono = men.children.create(name: "水着/着物・浴衣")
men_underwear = men.children.create(name: "アンダーウェア")
men_body = men.children.create(name: "ボディ・ヘアケア/コンタクト")
men_other = men.children.create(name: "その他")

# メンズの孫カテゴリ
men_tops.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ/ブラウス(半袖/袖なし)"}, {name: "シャツ/ブラウス(七分/長袖)"}, {name: "ポロシャツ"}, {name: "ニット・セーター"}, {name: "ベスト/ジレ"}, {name: "パーカー"}, {name: "トレーナー/スウェット"}, {name: "カーディガン/ボレロ"}, {name: "アンサンブル"}, {name: "ジャージ"}, {name: "タンクトップ"}, {name: "キャミソール"}, {name: "その他"}])
men_jacket.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "ライダースジャケット"}, {name: "ジャンパー/ブルゾン"}, {name: "カバーオール"}, {name: "ミリタリージャケット"}, {name: "MA-1"}, {name: "ダウンベスト"}, {name: "ダウンジャケット/コート"}, {name: "ダッフルコート"}, {name: "モッズコート"}, {name: "ピーコート"}, {name: "ステンカラーコート"}, {name: "トレンチコート"}, {name: "チェスターコート"}, {name: "ムートンコート"}, {name: "ナイロンジャケット"}, {name: "マウンテンパーカー"}, {name: "スタジャン"}, {name: "スカジャン"}, {name: "ポンチョ"}, {name: "その他"}])
men_overalls.children.create([{name: "オールインワン・サロペット"}, {name: "つなぎ・オールインワン"}, {name: "その他"}])
men_suits.children.create([{name: "スーツジャケット"}, {name: "スーツベスト"}, {name: "スーツパンツ"}, {name: "セットアップ"}, {name: "ネクタイ"}, {name: "蝶ネクタイ"}, {name: "ネクタイピン"}, {name: "カフリンクス"}, {name: "その他"}])
men_pants.children.create([{name: "デニム/ジーンズ"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "チノパン"}, {name: "スラックス"}, {name: "ショートパンツ"}, {name: "カジュアルパンツ"}, {name: "ハーフパンツ"}, {name: "クロップドパンツ"}, {name: "サルエルパンツ"}, {name: "ガウチョパンツ"}, {name: "その他"}])
men_shoes.children.create([{name: "スニーカー"}, {name: "スリッポン"}, {name: "サンダル"}, {name: "パンプス"}, {name: "ブーツ"}, {name: "ブーティ"}, {name: "ドレスシューズ"}, {name: "バレエシューズ"}, {name: "ローファー"}, {name: "モカシン/デッキシューズ"}, {name: "レインシューズ"}, {name: "ビーチサンダル"}, {name: "その他"}])
men_legwear.children.create([{name: "ソックス/靴下"}, {name: "タイツ・ストッキング"}, {name: "レギンス・スパッツ"}, {name: "レッグウォーマー"}, {name: "その他"}])
men_bag.children.create([{name: "ショルダーバッグ"}, {name: "トートバッグ"}, {name: "バックパック・リュック"}, {name: "ボストンバッグ"}, {name: "ボディバック/ウエストポーチ"}, {name: "ハンドバッグ"}, {name: "クラッチバッグ"}, {name: "メッセンジャーバッグ"}, {name: "ビジネスバッグ"}, {name: "スーツケース・・キャリーバッグ"}, {name: "ドラムバッグ"}, {name: "エコバッグ"}, {name: "かごバッグ"}, {name: "その他"}])
men_hat.children.create([{name: "キャップ"}, {name: "ハット"}, {name: "ニットキャップ・ビーニー"}, {name: "ハンチング・ベレー帽"}, {name: "キャスケット"}, {name: "サンバイザー"}, {name: "その他"}])
men_accessory.children.create([{name: "ネックレス"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "イヤリング(片耳用)"}, {name: "イヤリング(両耳用)"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "アンクレット"}, {name: "チョーカー"}, {name: "ブローチ・コサージュ"}, {name: "チャーム"}, {name: "その他"}])
men_hair.children.create([{name: "ヘアゴム"}, {name: "ヘアバンド"}, {name: "カチューシャ"}, {name: "バレッタ/ヘアクリップ"}, {name: "ヘアピン"}, {name: "シュシュ"}, {name: "ウィッグ"}, {name: "その他"}])
men_item.children.create([{name: "ストール/スヌード"}, {name: "マフラー・ショール"}, {name: "ベルト"}, {name: "サスペンダー"}, {name: "サングラス"}, {name: "メガネ"}, {name: "手袋"}, {name: "ネックウォーマー"}, {name: "イヤマフ"}, {name: "長傘"}, {name: "折りたたみ傘"}, {name: "レインコート/ポンチョ"}, {name: "付け襟"}, {name: "その他"}])
men_wallet.children.create([{name: "財布"}, {name: "コインケース/札入れ"}, {name: "名刺入れ"}, {name: "ポーチ"}, {name: "手鏡/コンパクト"}, {name: "ハンカチ/ハンドタオル"}, {name: "バンダナ・スカーフ"}, {name: "キーホルダー"}, {name: "キーケース/キーアクセサリー"}, {name: "ウォレットチェーン"}, {name: "パスケース"}, {name: "カードケース"}, {name: "パスポートケース"}, {name: "扇子・うちわ"}, {name: "その他"}])
men_clock.children.create([{name: "腕時計"}, {name: "置き時計"}, {name: "掛け時計"}, {name: "その他"}])
men_kimono.children.create([{name: "水着"}, {name: "ラッシュガード"}, {name: "着物"}, {name: "スイムグッズ"}, {name: "浴衣"}, {name: "和装小物"}, {name: "その他"}])
men_underwear.children.create([{name: "トランクス"}, {name: "ボクサーパンツ"}, {name: "ルームウェア"}, {name: "その他"}])
men_body.children.create([{name: "香水"}, {name: "コンタクトレンズ・カラコン"}, {name: "ボディクリーム"}, {name: "ボディスクラブ/ピーリング"}, {name: "日焼け止め"}, {name: "ハンドクリーム"}, {name: "シャンプー"}, {name: "コンディショナー/トリートメント"}, {name: "ヘアスタイリング/ヘアワックス"}, {name: "ヘアオイル/ヘアミルク"}, {name: "石鹸/ボディソープ"}, {name: "入浴剤"}, {name: "オーラルケア/歯磨きグッズ"}, {name: "その他"}])
men_other.children.create([{name: "福袋・福箱"}, {name: "ラッピングキッド"}, {name: "採寸ボディスーツ"}, {name: "その他"}])

# キッズ(レディース)の子カテゴリ
kidslady_tops = kidslady.children.create(name: "トップス")
kidslady_jacket = kidslady.children.create(name: "ジャケット/アウター")
kidslady_onepiece = kidslady.children.create(name: "ワンピース")
kidslady_overalls = kidslady.children.create(name: "オールインワン・サロペット")
kidslady_suits = kidslady.children.create(name: "スーツ/ネクタイ")
kidslady_skirt = kidslady.children.create(name: "スカート")
kidslady_pants = kidslady.children.create(name: "パンツ")
kidslady_shoes = kidslady.children.create(name: "シューズ")
kidslady_legwear = kidslady.children.create(name: "レッグウェア")
kidslady_bag = kidslady.children.create(name: "バッグ")
kidslady_hat = kidslady.children.create(name: "帽子")
kidslady_accessory = kidslady.children.create(name: "アクセサリー")
kidslady_hair = kidslady.children.create(name: "ヘアアクセサリー")
kidslady_item = kidslady.children.create(name: "ファッション雑貨")
kidslady_wallet = kidslady.children.create(name: "財布・小物")
kidslady_clock = kidslady.children.create(name: "時計")
kidslady_kimono = kidslady.children.create(name: "水着/着物・浴衣")
kidslady_underwear = kidslady.children.create(name: "アンダーウェア")
kidslady_body_body = kidslady_body.children.create(name: "ボディ・ヘアケア/コンタクト")
kidslady_body_other = kidslady_body.children.create(name: "その他")

# キッズ(レディース)の孫カテゴリ
kidslady_tops.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ/ブラウス(半袖/袖なし)"}, {name: "シャツ/ブラウス(七分/長袖)"}, {name: "ポロシャツ"}, {name: "ニット・セーター"}, {name: "ベスト/ジレ"}, {name: "パーカー"}, {name: "トレーナー/スウェット"}, {name: "カーディガン/ボレロ"}, {name: "アンサンブル"}, {name: "ジャージ"}, {name: "タンクトップ"}, {name: "キャミソール"}, {name: "その他"}])
kidslady_jacket.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "ライダースジャケット"}, {name: "ジャンパー/ブルゾン"}, {name: "カバーオール"}, {name: "ミリタリージャケット"}, {name: "MA-1"}, {name: "ダウンベスト"}, {name: "ダウンジャケット/コート"}, {name: "ダッフルコート"}, {name: "モッズコート"}, {name: "ピーコート"}, {name: "ステンカラーコート"}, {name: "トレンチコート"}, {name: "チェスターコート"}, {name: "ムートンコート"}, {name: "ナイロンジャケット"}, {name: "マウンテンパーカー"}, {name: "スタジャン"}, {name: "スカジャン"}, {name: "ポンチョ"}, {name: "その他"}])
kidslady_onepiece.children.create([{name: "ミニワンピース"}, {name: "ひざ丈ワンピース"}, {name: "ロングワンピース"}, {name: "シャツワンピース"}, {name: "ジャンパースカート"}, {name: "チュニック"}, {name: "ドレス"}, {name: "その他"}])
kidslady_overalls.children.create([{name: "オールインワン・サロペット"}, {name: "つなぎ・オールインワン"}, {name: "その他"}])
kidslady_suits.children.create([{name: "スーツジャケット"}, {name: "スーツベスト"}, {name: "スーツパンツ"}, {name: "スーツスカート"}, {name: "セットアップ"}, {name: "ネクタイ"}, {name: "蝶ネクタイ"}, {name: "ネクタイピン"}, {name: "カフリンクス"}, {name: "その他"}])
kidslady_skirt.children.create([{name: "ミニスカート"}, {name: "ひざ丈スカート"}, {name: "ロングスカート"}, {name: "デニムスカート"}, {name: "その他"}])
kidslady_pants.children.create([{name: "デニム/ジーンズ"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "チノパン"}, {name: "スラックス"}, {name: "ショートパンツ"}, {name: "カジュアルパンツ"}, {name: "ハーフパンツ"}, {name: "クロップドパンツ"}, {name: "サルエルパンツ"}, {name: "ガウチョパンツ"}, {name: "その他"}])
kidslady_shoes.children.create([{name: "スニーカー"}, {name: "スリッポン"}, {name: "サンダル"}, {name: "パンプス"}, {name: "ブーツ"}, {name: "ブーティ"}, {name: "ドレスシューズ"}, {name: "バレエシューズ"}, {name: "ローファー"}, {name: "モカシン/デッキシューズ"}, {name: "レインシューズ"}, {name: "ビーチサンダル"}, {name: "その他"}])
kidslady_legwear.children.create([{name: "ソックス/靴下"}, {name: "タイツ・ストッキング"}, {name: "レギンス・スパッツ"}, {name: "レッグウォーマー"}, {name: "その他"}])
kidslady_bag.children.create([{name: "ショルダーバッグ"}, {name: "トートバッグ"}, {name: "バックパック・リュック"}, {name: "ボストンバッグ"}, {name: "ボディバック/ウエストポーチ"}, {name: "ハンドバッグ"}, {name: "クラッチバッグ"}, {name: "メッセンジャーバッグ"}, {name: "ビジネスバッグ"}, {name: "スーツケース・・キャリーバッグ"}, {name: "ドラムバッグ"}, {name: "エコバッグ"}, {name: "かごバッグ"}, {name: "その他"}])
kidslady_hat.children.create([{name: "キャップ"}, {name: "ハット"}, {name: "ニットキャップ・ビーニー"}, {name: "ハンチング・ベレー帽"}, {name: "キャスケット"}, {name: "サンバイザー"}, {name: "その他"}])
kidslady_accessory.children.create([{name: "ネックレス"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "イヤリング(片耳用)"}, {name: "イヤリング(両耳用)"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "アンクレット"}, {name: "チョーカー"}, {name: "ブローチ・コサージュ"}, {name: "チャーム"}, {name: "その他"}])
kidslady_hair.children.create([{name: "ヘアゴム"}, {name: "ヘアバンド"}, {name: "カチューシャ"}, {name: "バレッタ/ヘアクリップ"}, {name: "ヘアピン"}, {name: "シュシュ"}, {name: "ウィッグ"}, {name: "その他"}])
kidslady_item.children.create([{name: "ストール/スヌード"}, {name: "マフラー・ショール"}, {name: "ベルト"}, {name: "サスペンダー"}, {name: "サングラス"}, {name: "メガネ"}, {name: "手袋"}, {name: "ネックウォーマー"}, {name: "イヤマフ"}, {name: "長傘"}, {name: "折りたたみ傘"}, {name: "レインコート/ポンチョ"}, {name: "付け襟"}, {name: "その他"}])
kidslady_wallet.children.create([{name: "財布"}, {name: "コインケース/札入れ"}, {name: "名刺入れ"}, {name: "ポーチ"}, {name: "手鏡/コンパクト"}, {name: "ハンカチ/ハンドタオル"}, {name: "バンダナ・スカーフ"}, {name: "キーホルダー"}, {name: "キーケース/キーアクセサリー"}, {name: "ウォレットチェーン"}, {name: "パスケース"}, {name: "カードケース"}, {name: "パスポートケース"}, {name: "扇子・うちわ"}, {name: "その他"}])
kidslady_clock.children.create([{name: "腕時計"}, {name: "置き時計"}, {name: "掛け時計"}, {name: "その他"}])
kidslady_kimono.children.create([{name: "水着"}, {name: "ラッシュガード"}, {name: "着物"}, {name: "スイムグッズ"}, {name: "浴衣"}, {name: "和装小物"}, {name: "その他"}])
kidslady_underwear.children.create([{name: "下着"}, {name: "ルームウェア"}, {name: "その他"}])
kidslady_body.children.create([{name: "香水"}, {name: "コンタクトレンズ・カラコン"}, {name: "ボディクリーム"}, {name: "ボディスクラブ/ピーリング"}, {name: "日焼け止め"}, {name: "ハンドクリーム"}, {name: "シャンプー"}, {name: "コンディショナー/トリートメント"}, {name: "ヘアスタイリング/ヘアワックス"}, {name: "ヘアオイル/ヘアミルク"}, {name: "石鹸/ボディソープ"}, {name: "入浴剤"}, {name: "オーラルケア/歯磨きグッズ"}, {name: "その他"}])
kidslady_other.children.create([{name: "福袋・福箱"}, {name: "ラッピングキッド"}, {name: "採寸ボディスーツ"}, {name: "その他"}])

# キッズ(ボーイ)の子カテゴリ
kidsboy_tops = kidsboy.children.create(name: "トップス")
kidsboy_jacket = kidsboy.children.create(name: "ジャケット/アウター")
kidsboy_overalls = kidsboy.children.create(name: "オールインワン・サロペット")
kidsboy_suits = kidsboy.children.create(name: "スーツ/ネクタイ")
kidsboy_pants = kidsboy.children.create(name: "パンツ")
kidsboy_shoes = kidsboy.children.create(name: "シューズ")
kidsboy_legwear = kidsboy.children.create(name: "レッグウェア")
kidsboy_bag = kidsboy.children.create(name: "バッグ")
kidsboy_hat = kidsboy.children.create(name: "帽子")
kidsboy_accessory = kidsboy.children.create(name: "アクセサリー")
kidsboy_hair = kidsboy.children.create(name: "ヘアアクセサリー")
kidsboy_item = kidsboy.children.create(name: "ファッション雑貨")
kidsboy_wallet = kidsboy.children.create(name: "財布・小物")
kidsboy_clock = kidsboy.children.create(name: "時計")
kidsboy_kimono = kidsboy.children.create(name: "水着/着物・浴衣")
kidsboy_underwear = kidsboy.children.create(name: "アンダーウェア")
kidsboy_body = kidsboy.children.create(name: "ボディ・ヘアケア/コンタクト")
kidsboy_other = kidsboy.children.create(name: "その他")

# キッズ(ボーイ)の孫カテゴリ
kidsboy_tops.children.create([{name: "Tシャツ/カットソー(半袖/袖なし)"}, {name: "Tシャツ/カットソー(七分/長袖)"}, {name: "シャツ/ブラウス(半袖/袖なし)"}, {name: "シャツ/ブラウス(七分/長袖)"}, {name: "ポロシャツ"}, {name: "ニット・セーター"}, {name: "ベスト/ジレ"}, {name: "パーカー"}, {name: "トレーナー/スウェット"}, {name: "カーディガン/ボレロ"}, {name: "アンサンブル"}, {name: "ジャージ"}, {name: "タンクトップ"}, {name: "キャミソール"}, {name: "その他"}])
kidsboy_jacket.children.create([{name: "テーラードジャケット"}, {name: "ノーカラージャケット"}, {name: "Gジャン/デニムジャケット"}, {name: "ライダースジャケット"}, {name: "ジャンパー/ブルゾン"}, {name: "カバーオール"}, {name: "ミリタリージャケット"}, {name: "MA-1"}, {name: "ダウンベスト"}, {name: "ダウンジャケット/コート"}, {name: "ダッフルコート"}, {name: "モッズコート"}, {name: "ピーコート"}, {name: "ステンカラーコート"}, {name: "トレンチコート"}, {name: "チェスターコート"}, {name: "ムートンコート"}, {name: "ナイロンジャケット"}, {name: "マウンテンパーカー"}, {name: "スタジャン"}, {name: "スカジャン"}, {name: "ポンチョ"}, {name: "その他"}])
kidsboy_overalls.children.create([{name: "オールインワン・サロペット"}, {name: "つなぎ・オールインワン"}, {name: "その他"}])
kidsboy_suits.children.create([{name: "スーツジャケット"}, {name: "スーツベスト"}, {name: "スーツパンツ"}, {name: "セットアップ"}, {name: "ネクタイ"}, {name: "蝶ネクタイ"}, {name: "ネクタイピン"}, {name: "カフリンクス"}, {name: "その他"}])
kidsboy_pants.children.create([{name: "デニム/ジーンズ"}, {name: "ワークパンツ/カーゴパンツ"}, {name: "チノパン"}, {name: "スラックス"}, {name: "ショートパンツ"}, {name: "カジュアルパンツ"}, {name: "ハーフパンツ"}, {name: "クロップドパンツ"}, {name: "サルエルパンツ"}, {name: "ガウチョパンツ"}, {name: "その他"}])
kidsboy_shoes.children.create([{name: "スニーカー"}, {name: "スリッポン"}, {name: "サンダル"}, {name: "パンプス"}, {name: "ブーツ"}, {name: "ブーティ"}, {name: "ドレスシューズ"}, {name: "バレエシューズ"}, {name: "ローファー"}, {name: "モカシン/デッキシューズ"}, {name: "レインシューズ"}, {name: "ビーチサンダル"}, {name: "その他"}])
kidsboy_legwear.children.create([{name: "ソックス/靴下"}, {name: "タイツ・ストッキング"}, {name: "レギンス・スパッツ"}, {name: "レッグウォーマー"}, {name: "その他"}])
kidsboy_bag.children.create([{name: "ショルダーバッグ"}, {name: "トートバッグ"}, {name: "バックパック・リュック"}, {name: "ボストンバッグ"}, {name: "ボディバック/ウエストポーチ"}, {name: "ハンドバッグ"}, {name: "クラッチバッグ"}, {name: "メッセンジャーバッグ"}, {name: "ビジネスバッグ"}, {name: "スーツケース・・キャリーバッグ"}, {name: "ドラムバッグ"}, {name: "エコバッグ"}, {name: "かごバッグ"}, {name: "その他"}])
kidsboy_hat.children.create([{name: "キャップ"}, {name: "ハット"}, {name: "ニットキャップ・ビーニー"}, {name: "ハンチング・ベレー帽"}, {name: "キャスケット"}, {name: "サンバイザー"}, {name: "その他"}])
kidsboy_accessory.children.create([{name: "ネックレス"}, {name: "リング"}, {name: "ピアス(片耳用)"}, {name: "ピアス(両耳用)"}, {name: "イヤリング(片耳用)"}, {name: "イヤリング(両耳用)"}, {name: "ブレスレット"}, {name: "バングル/リストバンド"}, {name: "アンクレット"}, {name: "チョーカー"}, {name: "ブローチ・コサージュ"}, {name: "チャーム"}, {name: "その他"}])
kidsboy_hair.children.create([{name: "ヘアゴム"}, {name: "ヘアバンド"}, {name: "カチューシャ"}, {name: "バレッタ/ヘアクリップ"}, {name: "ヘアピン"}, {name: "シュシュ"}, {name: "ウィッグ"}, {name: "その他"}])
kidsboy_item.children.create([{name: "ストール/スヌード"}, {name: "マフラー・ショール"}, {name: "ベルト"}, {name: "サスペンダー"}, {name: "サングラス"}, {name: "メガネ"}, {name: "手袋"}, {name: "ネックウォーマー"}, {name: "イヤマフ"}, {name: "長傘"}, {name: "折りたたみ傘"}, {name: "レインコート/ポンチョ"}, {name: "付け襟"}, {name: "その他"}])
kidsboy_wallet.children.create([{name: "財布"}, {name: "コインケース/札入れ"}, {name: "名刺入れ"}, {name: "ポーチ"}, {name: "手鏡/コンパクト"}, {name: "ハンカチ/ハンドタオル"}, {name: "バンダナ・スカーフ"}, {name: "キーホルダー"}, {name: "キーケース/キーアクセサリー"}, {name: "ウォレットチェーン"}, {name: "パスケース"}, {name: "カードケース"}, {name: "パスポートケース"}, {name: "扇子・うちわ"}, {name: "その他"}])
kidsboy_clock.children.create([{name: "腕時計"}, {name: "置き時計"}, {name: "掛け時計"}, {name: "その他"}])
kidsboy_kimono.children.create([{name: "水着"}, {name: "ラッシュガード"}, {name: "着物"}, {name: "スイムグッズ"}, {name: "浴衣"}, {name: "和装小物"}, {name: "その他"}])
kidsboy_underwear.children.create([{name: "トランクス"}, {name: "ボクサーパンツ"}, {name: "ルームウェア"}, {name: "その他"}])
kidsboy_body.children.create([{name: "香水"}, {name: "コンタクトレンズ・カラコン"}, {name: "ボディクリーム"}, {name: "ボディスクラブ/ピーリング"}, {name: "日焼け止め"}, {name: "ハンドクリーム"}, {name: "シャンプー"}, {name: "コンディショナー/トリートメント"}, {name: "ヘアスタイリング/ヘアワックス"}, {name: "ヘアオイル/ヘアミルク"}, {name: "石鹸/ボディソープ"}, {name: "入浴剤"}, {name: "オーラルケア/歯磨きグッズ"}, {name: "その他"}])
kidsboy_other.children.create([{name: "福袋・福箱"}, {name: "ラッピングキッド"}, {name: "採寸ボディスーツ"}, {name: "その他"}])

# ベビーの子カテゴリ
baby_girl = baby.children.create(name: "ベビー服(女の子用)")
baby_boy = baby.children.create(name: "ベビー服(男の子用)")
baby_item = baby.children.create(name: "ベビー用品")
baby_toilet = baby.children.create(name: "おむつ/トイレ/バス")
baby_other = baby.children.create(name: "その他")
# ベビーの孫カテゴリ
baby_girl.children.create([{name: "マタニティウェア"}, {name: "ロンパース"}, {name: "肌着"}, {name: "その他"}])
baby_boy.children.create([{name: "マタニティウェア"}, {name: "ロンパース"}, {name: "肌着"}, {name: "その他"}])
baby_item.children.create([{name: "マタニティグッズ"}, {name: "スタイ/よだれかけ"}, {name: "おくるみ"}, {name: "ベビーシューズ"}, {name: "その他"}])
baby_toilet.children.create([{name: "マザーバッグ/収納ポーチ"}, {name: "おむつ用品"}, {name: "ベビーカー用品"}, {name: "トレーニングパンツ"}, {name: "ベビーバス"}, {name: "お風呂用品"}, {name: "その他"}])
baby_other.children.create([{name: "母子手帳ケース"}, {name: "お食事グッズ"}, {name: "ベビーギフト"}, {name: "アルバム"}, {name: "手形/足形"}, {name: "その他"}])

# 美容の子カテゴリ
beauty_base = beauty.children.create(name: "ベースメイク")
beauty_makeup = beauty.children.create(name: "メイクアップ")
beauty_nail = beauty.children.create(name: "ネイルケアー")
beauty_perfume = beauty.children.create(name: "香水")
beauty_skincare = beauty.children.create(name: "スキンケア/基礎化粧品")
beauty_relaxation = beauty.children.create(name: "リラクゼーション")
beauty_diet = beauty.children.create(name: "ダイエット")
beauty_other = beauty.children.create(name: "その他")

# 美容の孫カテゴリ
beauty_base.children.create([{name: "ファンデーション"}, {name: "化粧下地"}, {name: "コントロールカラー"}, {name: "BBクリーム"}, {name: "CCクリーム"}, {name: "コンシーラー"}, {name: "フェイスパウダー"}, {name: "トライアルセット/サンプル"}, {name: "その他"}])
beauty_makeup.children.create([{name: "アイシャドウ"}, {name: "口紅"}, {name: "リップグロス"}, {name: "リップライナー"}, {name: "チーク"}, {name: "フェイスカラー"}, {name: "マスカラ"}, {name: "アイライナー"}, {name: "つけまつげ"}, {name: "アイブロウペンシル"}, {name: "パウダーアイブロウ"}, {name: "眉マスカラ"}, {name: "トライアルセット/サンプル"}, {name: "メイク道具/化粧小物"}, {name: "美顔用品/美顔ローラー"}, {name: "その他"}])
beauty_nail.children.create([{name: "ネイルカラー"}, {name: "カラージェル"}, {name: "ネイルベースコート/トップコート"}, {name: "ネイルアート用品"}, {name: "ネイルパーツ"}, {name: "ネイルチップ/付け爪"}, {name: "手入れ用具"}, {name: "除光液"}, {name: "その他"}])
beauty_perfume.children.create([{name: "香水(女性用)"}, {name: "香水(男性用)"}, {name: "ユニセックス"}, {name: "ボディミスト"}, {name: "その他"}])
beauty_skincare.children.create([{name: "化粧水/ローション"}, {name: "乳液/ミルク"}, {name: "美容液"}, {name: "フェイスクリーム"}, {name: "洗顔料"}, {name: "クレンジング/メイク落とし"}, {name: "パック/フェイスマスク"}, {name: "ジェル/ゲル"}, {name: "ブースター/導乳液"}, {name: "アイケア"}, {name: "リップケア"}, {name: "洗顔グッズ"}, {name: "その他"}])
beauty_relaxation.children.create([{name: "エッセンシャルオイル"}, {name: "芳香機"}, {name: "お香/香炉"}, {name: "キャンドル"}, {name: "リラクゼーショングッズ"}, {name: "その他"}])
beauty_diet.children.create([{name: "エクササイズ用品"}, {name: "体重計"}, {name: "その他"}])
beauty_other.children.create([{name: "健康用品"}, {name: "看護/介護用品"}, {name: "救急/衛生用品"}, {name: "その他"}])

# 本の子カテゴリ
book_book = book.children.create(name: "本")
book_manga = book.children.create(name: "漫画")
book_cd = book.children.create(name: "CD")
book_dvd = book.children.create(name: "DVD/ブルーレイ")
book_game = book.children.create(name: "テレビゲーム")
# 本の孫カテゴリ
book_book.children.create([{name: "文学/小説"}, {name: "人文/社会"}, {name: "ノンフィクション/教養"}, {name: "地図/旅行ガイド"}, {name: "ビジネス/経済"}, {name: "健康/医学"}, {name: "コンピュータ/IT"}, {name: "趣味/スポーツ/実用"}, {name: "住まい/暮らし/子育て"}, {name: "アート/エンタメ"}, {name: "洋書"}, {name: "絵本"}, {name: "参考書"}, {name: "その他"}])
book_manga.children.create([{name: "全巻セット"}, {name: "少年漫画"}, {name: "少女漫画"}, {name: "青年漫画"}, {name: "女性漫画"}, {name: "同人誌"}, {name: "その他"}])
book_cd.children.create([{name: "邦楽"}, {name: "洋楽"}, {name: "アニメ"}, {name: "クラシック"}, {name: "K-POP/アジア"}, {name: "キッズ/ファミリー"}, {name: "その他"}])
book_dvd.children.create([{name: "外国映画"}, {name: "日本映画"}, {name: "アニメ"}, {name: "TVドラマ"}, {name: "お笑い/バラエティ"}, {name: "スポーツ/フィットネス"}, {name: "キッズ/ファミリー"}, {name: "その他"}])
book_game.children.create([{name: "家庭用ゲーム本体"}, {name: "家庭用ゲームソフト"}, {name: "携帯用ゲーム本体"}, {name: "携帯用ゲームソフト"}, {name: "PCゲーム"}, {name: "その他"}])

# スポーツの子カテゴリ
sport_golf = sport.children.create(name: "ゴルフ")
sport_fishing = sport.children.create(name: "フィッシング")
sport_bicycle = sport.children.create(name: "自転車")
sport_training = sport.children.create(name: "トレーニング/エクササイズ")
sport_baseball = sport.children.create(name: "野球")
sport_soccer = sport.children.create(name: "サッカー/フットサル")
sport_tennis = sport.children.create(name: "テニス")
sport_snowboard = sport.children.create(name: "スノーボード")
sport_ski = sport.children.create(name: "スキー")
sport_other1 = sport.children.create(name: "その他スポーツ")
sport_outdoor = sport.children.create(name: "アウトドア")
sport_other2 = sport.children.create(name: "その他")

# スポーツの孫カテゴリ
sport_golf.children.create([{name: "クラブ"}, {name: "ウエア(女性用)"}, {name: "ウェア(男性用)"}, {name: "バッグ"}, {name: "シューズ(女性用)"}, {name: "シューズ(男性用)"}, {name: "アクセサリー"}, {name: "その他"}])
sport_fishing.children.create([{name: "ロッド"}, {name: "リール"}, {name: "ルアー用品"}, {name: "ウェア"}, {name: "釣り糸/ライン"}, {name: "その他"}])
sport_bicycle.children.create([{name: "自転車本体"}, {name: "ウェア"}, {name: "パーツ"}, {name: "アクセサリー"}, {name: "バッグ"}, {name: "工具/メンテナンス"}, {name: "その他"}])
sport_training.children.create([{name: "ランニング"}, {name: "ウォーキング"}, {name: "ヨガ"}, {name: "トレーニング用品"}, {name: "その他"}])
sport_baseball.children.create([{name: "ウェア"}, {name: "シューズ"}, {name: "グローブ"}, {name: "バット"}, {name: "アクセサリー"}, {name: "防具"}, {name: "練習機器"}, {name: "記念グッズ"}, {name: "応援グッズ"}, {name: "その他"}])
sport_soccer.children.create([{name: "ウェア"}, {name: "シューズ"}, {name: "ボール"}, {name: "アクセサリー"}, {name: "記念グッズ"}, {name: "応援グッズ"}, {name: "その他"}])
sport_tennis.children.create([{name: "テニス(硬式用)"}, {name: "テニス(軟式用)"}, {name: "ウェア"}, {name: "シューズ"}, {name: "ボール"}, {name: "アクセサリー"}, {name: "記念グッズ"}, {name: "応援グッズ"}, {name: "その他"}])
sport_snowboard.children.create([{name: "ボード"}, {name: "バインディング"}, {name: "ブーツ(女性用)"}, {name: "ブーツ(男性用)"}, {name: "ブーツ(子ども用)"}, {name: "ウェア/装備(女性用)"}, {name: "ウェア/装備(男性用)"}, {name: "ウェア/装備(子ども用)"}, {name: "アクセサリー"}, {name: "バッグ"}, {name: "その他"}])
sport_ski.children.create([{name: "板"}, {name: "ブーツ(女性用)"}, {name: "ブーツ(男性用)"}, {name: "ブーツ(子ども用)"}, {name: "ビンディング"}, {name: "ウェア/装備(女性用)"}, {name: "ウェア/装備(男性用)"}, {name: "ウェア/装備(子ども用)"}, {name: "ストック"}, {name: "その他"}])
sport_other1.children.create([{name: "ダンス/バレエ"}, {name: "サーフィン"}, {name: "バスケットボール"}, {name: "バドミントン"}, {name: "バレーボール"}, {name: "スケートボード"}, {name: "陸上競技"}, {name: "ラグビー"}, {name: "アメリカンフットボール"}, {name: "ボクシング"}, {name: "ボウリング"}, {name: "その他"}])
sport_outdoor.children.create([{name: "テント/タープ"}, {name: "テント/ランタン"}, {name: "寝袋/寝具"}, {name: "テーブル/チェア"}, {name: "ストーブ/コンロ"}, {name: "調理器具"}, {name: "食器"}, {name: "登山用品"}, {name: "その他"}])
sport_other2.children.create([{name: "旅行用品"}, {name: "その他"}])

# 服サイズ
clothes = ItemsSize.create(size: "服のサイズ")
clothes_1 = clothes.children.create(size: "XXS以下")
clothes_2 = clothes.children.create(size: "XS（SS）")
clothes_3 = clothes.children.create(size: "S")
clothes_4 = clothes.children.create(size: "M")
clothes_5 = clothes.children.create(size: "L")
clothes_6 = clothes.children.create(size: "XL(LL)")
clothes_7 = clothes.children.create(size: "2XL(3L)")
clothes_8 = clothes.children.create(size: "3XL(4L)")
clothes_9 = clothes.children.create(size: "4XL(5L)以上")
clothes_10 = clothes.children.create(size: "FREE SIZE")
# 靴のサイズ
women_shoes = ItemsSize.create(size: "靴のサイズ（女性）")
women_shoes_1 = women_shoes.children.create(size: "20cm以下")
women_shoes_2 = women_shoes.children.create(size: "20.5cm")
women_shoes_3 = women_shoes.children.create(size: "21cm")
women_shoes_4 = women_shoes.children.create(size: "21.5cm")
women_shoes_5 = women_shoes.children.create(size: "22cm")
women_shoes_6 = women_shoes.children.create(size: "22.5cm")
women_shoes_7 = women_shoes.children.create(size: "23cm")
women_shoes_8 = women_shoes.children.create(size: "23.5cm")
women_shoes_9 = women_shoes.children.create(size: "24cm")
women_shoes_10 = women_shoes.children.create(size: "24.5cm")
women_shoes_11 = women_shoes.children.create(size: "25cm")
women_shoes_12 = women_shoes.children.create(size: "25.5cm")
women_shoes_13 = women_shoes.children.create(size: "26cm")
women_shoes_14 = women_shoes.children.create(size: "26.5cm")
women_shoes_15 = women_shoes.children.create(size: "27cm")
women_shoes_16 = women_shoes.children.create(size: "27.5cm以上")

category_size = CategorySize.create({category_id: lady_tops.children.ids,items_size_id:clothes.id})
category_size = CategorySize.create({category_id: lady_jacket.children.ids,items_size_id:clothes.id})
category_size = CategorySize.create({category_id: lady_pants.children.ids,items_size_id:clothes.id})
category_size = CategorySize.create({category_id: lady_skirt.children.ids,items_size_id:clothes.id})
category_size = CategorySize.create({category_id: lady_onepiece.children.ids,items_size_id:clothes.id})
category_size = CategorySize.create({category_id: lady_other.children.ids,items_size_id:clothes.id})