class Brand < ActiveHash::Base
  self.data = [
    
    { id: 1, name: 'UNIQLO(ユニクロ)' },
    { id: 2, name: 'GU(ジーユー)' },
    { id: 3, name: 'CONVERSE(コンバース)' },
    { id: 4, name: 'NIKE(ナイキ)' },
    { id: 5, name: 'ZARA(ザラ)' },
    { id: 6, name: 'WEGO(ウィゴー)' },
    { id: 7, name: 'H&M(エイチ・アンド・エム)' },
    { id: 8, name: 'no brand(ノーブランド)' },
    { id: 9, name: 'adidas(アディダス)' },
    { id: 10, name: 'HYSTERIC GLAMOUR(ヒステリックグラマー)' },
    { id: 11, name: 'GLOBAL WORK(グローバルワーク)' },
    { id: 12, name: 'VANS(バンズ)' },
    { id: 13, name: 'Dr.Martens(ドクターマーチン)' },
    { id: 14, name: 'LOWRYS FARM(ローリーズファーム)' },
    { id: 15, name: 'earth music&ecology(アースミュージックアンドエコロジー)' },
    { id: 16, name: 'しまむら(シマムラ)' },
    { id: 17, name: 'NEW BALANCE(ニューバランス)' },
    { id: 18, name: 'HARE(ハレ)' },
    { id: 19, name: 'RAGEBLUE(レイジブルー)' },
    { id: 20, name: '無印良品(ムジルシリョウヒン)' },
    { id: 21, name: 'niko and...(ニコアンド)' },
    { id: 22, name: 'GAP(ギャップ)' },
    { id: 23, name: 'BRAUTY&YOUTH UNITED ARROWS(ビューティアンドユースユナイテッドアローズ)' },
    { id: 24, name: 'Ungrid(アングリッド)' },
    { id: 25, name: 'nano・universe(ナノユニバース)' },
    { id: 26, name: 'URBAN RESEARCH(アーバンリサーチ)' },
    { id: 27, name: 'JEANASIS(ジーナシス)' },
    { id: 28, name: 'VINTAGE(ヴィンテージ)' },
    { id: 29, name: 'petit main(プティマイン)' },
    { id: 30, name: 'Champion(チャンピオン)' },
    { id: 31, name: 'DIESEL(ディーゼル)' },
    { id: 32, name: 'MOUSSY(マウジー)' },
    { id: 33, name: 'AVIREX(アヴィレックス)' },
    { id: 34, name: 'FREAK’S STORE(フリークスストア)' },
    { id: 35, name: 'FOREVER 21(フォーエバー トゥエンティーワン)' },
    { id: 36, name: 'Levi’s(リーバイス)' },
    { id: 37, name: 'Handmade(ハンドメイド)' },
    { id: 38, name: '西松屋(ニシマツヤ)' },
    { id: 39, name: 'Samansa Mos2(サマンサ モスモス)' },
    { id: 40, name: 'MAJESTIC LEGON(マジェスティック レゴン)' },
    { id: 41, name: 'SENSE OF PLACE by URBAN RESEARCH(センス オブ レイス バイ アーバンリサーチ)' },
    { id: 42, name: 'JOURNAL STANDARD(ジャーナルスタンダード)' },
    { id: 43, name: 'Daniel Wellington(ダニエルウェリントン)' },
    { id: 44, name: 'Supreme(シュプリーム)' },
    { id: 45, name: 'THE NORTH FACE(ザ ノースフェイス)' },
    { id: 46, name: 'Kastane(カスタネ)' },
    { id: 47, name: 'green label relaxing(グリーンレーベルリラクシング)' },
    { id: 48, name: 'adidas originals(アディダスオリジナルス)' },
    { id: 49, name: 'TODAYFUL(トゥデイフル)' },
    { id: 50, name: 'coen(コーエン)' },
    { id: 51, name: 'BEAMS(ビームス)' },
    { id: 52, name: 'Lee(リー)' },
    { id: 53, name: 'GRL(グレイル)' },
    { id: 54, name: 'Reebok(リーボック)' },
    { id: 55, name: 'KBF(ケイビーエフ)' },
    { id: 56, name: 'LEPSIM(レプシィム)' },
    { id: 57, name: 'babyGAP(babyGAP)' },
    { id: 58, name: 'AZUL by moussy(アズールバイマウジー)' },
    { id: 59, name: 'INGNI(イング)' },
    { id: 60, name: 'CIAOPANIC TYPY(チャオパニックティピー)' },
    { id: 61, name: 'Birthday(バースディ)' },
    { id: 62, name: '靴下屋(クツシタヤ)' },
    { id: 63, name: 'studio CLIP(スタディオクリック)' },
    { id: 64, name: 'DHOLIC(ディホリック)' },
    { id: 65, name: 'Ciaopanic(チャオパニック)' },
    { id: 66, name: 'BRANSHES(ブランシェス)' },
    { id: 67, name: 'Heather(ヘザー)' },
    { id: 68, name: 'OLD NAVY(オールドネイビー)' },
    { id: 69, name: 'BEAMS BOY(ビームスボーイ)' },
    { id: 70, name: 'Honeys(ハニーズ)' },
    { id: 71, name: 'E hyphen world gallery(イーハイフンワールドギャラリー)' },
    { id: 72, name: 'Green Parks(グリーンパークス)' },
    { id: 73, name: 'POLO RALPH LAUREN(ポロラルフローレン)' },
    { id: 74, name: 'SPINNS(スピンズ)' },
    { id: 75, name: 'STUDIOUS(ステュディオス)' },
    { id: 76, name: 'w closet(ダブルクローゼット)' },
    { id: 77, name: 'BIRKENSTOCK(ビルケンシュトック)' },
    { id: 78, name: 'ADAM ET ROPE’(アダムエロペ)' },
    { id: 79, name: 'Another Edition(アナザーエディション)' },
    { id: 80, name: 'mystic(ミスティック)' },
    { id: 81, name: 'SLY(スライ)' },
    { id: 82, name: 'Right-on(ライトオン)' },
    { id: 83, name: 'BREEZE(ブリーズ)' },
    { id: 84, name: 'STUSSY(ステューシー)' },
    { id: 85, name: 'RETRO GIRL(レトロガール)' },
    { id: 86, name: 'Dickies(ディッキーズ)' },
    { id: 87, name: 'ORiental TRaffic(オリエンタルトラフィック)' },
    { id: 88, name: 'Ray BEAMS(レイビームス)' },
    { id: 89, name: 'Bershka(ベルシュカ)' },
    { id: 90, name: 'PAGEBOY(ページボーイ)' },
    { id: 91, name: 'G-SHOCK(ジーショック)' },
    { id: 92, name: 'SNIDEL(スナイデル)' },
    { id: 93, name: 'LIDNM(リドム)' },
    { id: 94, name: 'UNITED ARROWS(ユナイテッドアローズ)' },
    { id: 95, name: 'SLOBE IENA(スローブイエナ)' },
    { id: 96, name: 'ZARA KIDS' },
    { id: 97, name: 'GUCCI(グッチ)' },
    { id: 98, name: 'JOURNAL STANDARD relume(ジャーナルスタンダード レリューム)' },
    { id: 99, name: 'who’s sho Chico(フーズフーチコ)' },
    { id: 100, name: 'CASIO(カシオ)' },

    # 必須項目のため空のバリューを用意
    { id: 101, name: 'その他' }
  ]
end